# Changes here will be overwritten by Copier
_commit: v2.2.6
_src_path: https://github.com/phil65/copier-phil65.git
author_email: philipptemminghoff@googlemail.com
author_fullname: Philipp Temminghoff
author_username: phil65
copyright_date: "2025"
copyright_holder: Philipp Temminghoff
copyright_holder_email: philipptemminghoff@googlemail.com
libraries_use_pydantic: true
libraries_use_qt: false
project_description: Execution environments
project_name: Exxec
python_minimum_version: "3.13"
python_package_command_line_name: exxec
python_package_distribution_name: exxec
python_package_import_name: exxec
repository_name: exxec
repository_namespace: phil65
repository_provider: github.com
